# Generated by Django 5.0.6 on 2024-06-26 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_cupomdesconto_alter_pedido_data_pedido_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 15, 42, 2, 805274)),
        ),
    ]
